language: java
jdk:
#  - openjdk6
#  - oraclejdk7
  - openjdk7
  - oraclejdk8

branches:
  except:
    - appveyor

after_success:
  - mvn clean cobertura:cobertura coveralls:report

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
